# Generated by Django 5.0.7 on 2024-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='date',
            field=models.DateField(max_length=20),
        ),
    ]
