# Generated by Django 5.0.7 on 2024-08-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_alter_feedbackform_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackform',
            name='phone',
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
