# Generated by Django 5.0.7 on 2024-08-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_remove_feedbackform_phone_feedbackform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackform',
            name='date',
        ),
    ]
